development:
  adapter: postgresql
  encoding: UTF8
  database: youtube-dj_development
  host: localhost
  pool: 5

test: &test
  adapter: postgresql
  encoding: UTF8
  database: youtube-dj_test 
  host: localhost
  pool: 5
  min_messages: WARNING

